### ISSUE TITLE
ldap.SERVER_DOWN: {'result': -1, 'desc': "Can't contact LDAP server"

### ISSUE THREAD

**Issue by grillorj** [Universidad-Tecnologica-CUJAE/AD-webmanager#105]
2023-03-28 10:46:45 | INFO | 10.230.43.173 - - [28/Mar/2023 10:46:45] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2023-03-28 10:46:45 | INFO | 10.230.43.173 - - [28/Mar/2023 10:46:45] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2023-03-28 10:46:45 | INFO | 10.230.43.173 - - [28/Mar/2023 10:46:45] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2023-03-28 10:46:45 | INFO | 10.230.43.173 - - [28/Mar/2023 10:46:45] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2023-03-28 10:46:45 | INFO | 10.230.43.173 - - [28/Mar/2023 10:46:45] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2023-03-28 10:46:48 | INFO | 10.230.43.173 - - [28/Mar/2023 10:46:48] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/AD-webmanager/libs/ldap_func.py", line 625, in _decorator
    if not auth or not _ldap_connect(auth.username, auth.password):
  File "/AD-webmanager/libs/ldap_func.py", line 537, in _ldap_connect
    connection.simple_bind_s("%s@%s" % (username, g.ldap['domain']),
  File "/venv/lib/python3.10/site-packages/ldap/ldapobject.py", line 248, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/venv/lib/python3.10/site-packages/ldap/ldapobject.py", line 242, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/venv/lib/python3.10/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)

**Comment by lupo1st** [comment]
I have the same Problem... Did anyone fnd a solution???

**Comment by VicentGJ** [comment]
Sorry, but I'm not able to reproduce this issue, sorry for the delayed answer. Maybe you could provide the .env and settings.py files you are using to see if I can spot any misconfiguration and more insight into the problem.

**Comment by lupo1st** [comment]
I will send you a Mail later, with the files requested. Thank you

**Comment by lupo1st** [comment]
By the way... is it a LDAPS or LDAP connection??

**Comment by 4integration** [comment]
Same error here

**Comment by 4integration** [comment]
> By the way... is it a LDAPS or LDAP connection??

Saw this https://github.com/VicentGJ/AD-webmanager/blob/90fd34e77aa131a7d2724d597798b9ea60ea1133/libs/ldap_func.py#L535

Changed to ldap for my tests, removed the error but cannot login
